name: rdkit
channels:
    - conda-forge
dependencies:
    - python=3.9.12
    - matplotlib=3.5.2
    - seaborn=0.11.2
    - rdkit=2021.03
    - jupyter
    - pandas
    - numpy
    - networkx
    - pip
